### ISSUE TITLE
All feedback is showing as against unmodified files

### ISSUE THREAD

**Issue by graemethomsongold** [thienan93/phdiff#3] opened 2017-11-23 15:47 UTC
Cool plugin - I'd love to help contrib.  Currently all the comments coming back are showing as below - even though Phabricator does know they are in the revision.

Any ideas??

Unmodified file :9F8A0472-DDA8-4BA7-9D28-F9C0FB7A8A93:ShiftBidding.cs on line 18

 Rename method "myNewAction" to match camel case naming rules, consider using "MyNewAction". View rule

**Comment by nthienan** [comment] 2017-11-24 09:30
I think it's safe to be ignored and not counted in global comment.

**Comment by nthienan** [comment] 2017-11-25 04:00
Your project was not scaned by Sonar before. So all issues are new and shown on Phabricator

**Comment by billiechar** [comment] 2017-11-26 09:46
I am also seeing this problem. The code is fully scanned and recognised in sonarqube, but when phabricator is triggering a build the plugin will correctly report the errors only in the submitted code. However the changes are reported in comments as unmodified file:9F8A0472-DDA8-4BA7-9D28-F9C0FB7A8A93 has an error instead of appearing inline as expected

**Comment by nthienan** [comment] 2017-11-26 10:34
@billiechar, please see #2. So what do you want in that case?

**Comment by billiechar** [comment] 2017-11-26 11:02
It looks like the plugin is trying to find the file as 9F8A0472-DDA8-4BA7-9D28-F9C0FB7A8A93:myFile.cs instead of looking into the actual subdirectories. Only SonarQube knows about the ID being displayed as Phabricator only knows about its actual filepath of /folder1/folder2/myFile.cs. 
#2 is the correct process if the file does not exist, but in this case the file does exist, it is just trying to locate it using the ID instead of the filepath which seems to be incorrect

**Comment by nthienan** [comment] 2017-11-26 11:08
ah ah, which sonar version that you are using?

**Comment by billiechar** [comment] 2017-11-26 11:09
Version 6.7 (build 33306)

**Comment by nthienan** [comment] 2018-11-08 03:17
@graemethomsongold @billiechar do you have time to help me on this issue?

**Comment by billiechar** [comment] 2018-11-15 12:24
> @graemethomsongold @billiechar do you have time to help me on this issue?

sorry for the late reply, I have solved this on my machine at work but I don't have access to the solution until Monday. It worked for my c# project but hasn't been tested against other languages.

The problem is with line 59 in      phdiff/src/main/kotlin/io/nthienan/phdiff/PhabricatorDifferentialPostJob.kt

val filePath = i.componentKey().replace(projectKey, "").substring(1)

One of the other methods on i looks to just store the file path directly so you can use that instead of splitting the project name, but without my altered code, I can't remember the method sorry.

**Comment by nthienan** [comment] 2018-11-19 04:48
@billiechar, great to hear that you solved the issue. It would be nice if you open a PR for the issue when you're able to access your solution. I happily accept and merge your PR.

**Comment by nthienan** [comment] 2018-11-19 10:04
I'm going to close this since PR #6 has been merged

**Closed as completed by nthienan** 2018-11-19 10:04 UTC
Labels: help wanted
